# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from chronos.services.chargelocation.v1 import chargelocation_service_pb2 as chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in chronos/services/chargelocation/v1/chargelocation_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChargeLocationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddDepartureTime = channel.unary_unary(
                '/chronos.services.v1.ChargeLocationService/AddDepartureTime',
                request_serializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.AddDepartureTimeToChargeLocationRequest.SerializeToString,
                response_deserializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.AddDepartureTimeToChargeLocationResponse.FromString,
                _registered_method=True)
        self.AddTimer = channel.unary_unary(
                '/chronos.services.v1.ChargeLocationService/AddTimer',
                request_serializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.AddTimerToChargeLocationRequest.SerializeToString,
                response_deserializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.AddTimerToChargeLocationResponse.FromString,
                _registered_method=True)
        self.CreateAtTheCarLocation = channel.unary_unary(
                '/chronos.services.v1.ChargeLocationService/CreateAtTheCarLocation',
                request_serializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.CreateAtTheCarLocationRequest.SerializeToString,
                response_deserializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.CreateAtTheCarLocationResponse.FromString,
                _registered_method=True)
        self.DeleteLocation = channel.unary_unary(
                '/chronos.services.v1.ChargeLocationService/DeleteLocation',
                request_serializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.DeleteChargeLocationRequest.SerializeToString,
                response_deserializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.DeleteChargeLocationResponse.FromString,
                _registered_method=True)
        self.GetChargeLocations = channel.unary_unary(
                '/chronos.services.v1.ChargeLocationService/GetChargeLocations',
                request_serializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.GetChargeLocationsRequest.SerializeToString,
                response_deserializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.GetChargeLocationsResponse.FromString,
                _registered_method=True)
        self.isAtALocation = channel.unary_unary(
                '/chronos.services.v1.ChargeLocationService/isAtALocation',
                request_serializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.IsAtLocationRequest.SerializeToString,
                response_deserializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.IsAtLocationResponse.FromString,
                _registered_method=True)
        self.UpdateAlias = channel.unary_unary(
                '/chronos.services.v1.ChargeLocationService/UpdateAlias',
                request_serializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationAliasRequest.SerializeToString,
                response_deserializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationAliasResponse.FromString,
                _registered_method=True)
        self.UpdateAmpLimit = channel.unary_unary(
                '/chronos.services.v1.ChargeLocationService/UpdateAmpLimit',
                request_serializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationAmpLimitRequest.SerializeToString,
                response_deserializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationAmpLimitResponse.FromString,
                _registered_method=True)
        self.UpdateDepartureTime = channel.unary_unary(
                '/chronos.services.v1.ChargeLocationService/UpdateDepartureTime',
                request_serializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationDepartureTimeRequest.SerializeToString,
                response_deserializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationDepartureTimeResponse.FromString,
                _registered_method=True)
        self.UpdateMinimumSoc = channel.unary_unary(
                '/chronos.services.v1.ChargeLocationService/UpdateMinimumSoc',
                request_serializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationMinimumSocRequest.SerializeToString,
                response_deserializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationMinimumSocResponse.FromString,
                _registered_method=True)
        self.UpdateOptimizedSetting = channel.unary_unary(
                '/chronos.services.v1.ChargeLocationService/UpdateOptimizedSetting',
                request_serializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateOptimizedSettingRequest.SerializeToString,
                response_deserializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateOptimizedSettingResponse.FromString,
                _registered_method=True)
        self.UpdateTimer = channel.unary_unary(
                '/chronos.services.v1.ChargeLocationService/UpdateTimer',
                request_serializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationTimerRequest.SerializeToString,
                response_deserializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationTimerResponse.FromString,
                _registered_method=True)


class ChargeLocationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddDepartureTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddTimer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAtTheCarLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChargeLocations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def isAtALocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAlias(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAmpLimit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDepartureTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMinimumSoc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateOptimizedSetting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTimer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChargeLocationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddDepartureTime': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDepartureTime,
                    request_deserializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.AddDepartureTimeToChargeLocationRequest.FromString,
                    response_serializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.AddDepartureTimeToChargeLocationResponse.SerializeToString,
            ),
            'AddTimer': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTimer,
                    request_deserializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.AddTimerToChargeLocationRequest.FromString,
                    response_serializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.AddTimerToChargeLocationResponse.SerializeToString,
            ),
            'CreateAtTheCarLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAtTheCarLocation,
                    request_deserializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.CreateAtTheCarLocationRequest.FromString,
                    response_serializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.CreateAtTheCarLocationResponse.SerializeToString,
            ),
            'DeleteLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteLocation,
                    request_deserializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.DeleteChargeLocationRequest.FromString,
                    response_serializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.DeleteChargeLocationResponse.SerializeToString,
            ),
            'GetChargeLocations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChargeLocations,
                    request_deserializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.GetChargeLocationsRequest.FromString,
                    response_serializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.GetChargeLocationsResponse.SerializeToString,
            ),
            'isAtALocation': grpc.unary_unary_rpc_method_handler(
                    servicer.isAtALocation,
                    request_deserializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.IsAtLocationRequest.FromString,
                    response_serializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.IsAtLocationResponse.SerializeToString,
            ),
            'UpdateAlias': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAlias,
                    request_deserializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationAliasRequest.FromString,
                    response_serializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationAliasResponse.SerializeToString,
            ),
            'UpdateAmpLimit': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAmpLimit,
                    request_deserializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationAmpLimitRequest.FromString,
                    response_serializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationAmpLimitResponse.SerializeToString,
            ),
            'UpdateDepartureTime': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDepartureTime,
                    request_deserializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationDepartureTimeRequest.FromString,
                    response_serializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationDepartureTimeResponse.SerializeToString,
            ),
            'UpdateMinimumSoc': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMinimumSoc,
                    request_deserializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationMinimumSocRequest.FromString,
                    response_serializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationMinimumSocResponse.SerializeToString,
            ),
            'UpdateOptimizedSetting': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateOptimizedSetting,
                    request_deserializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateOptimizedSettingRequest.FromString,
                    response_serializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateOptimizedSettingResponse.SerializeToString,
            ),
            'UpdateTimer': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTimer,
                    request_deserializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationTimerRequest.FromString,
                    response_serializer=chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationTimerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chronos.services.v1.ChargeLocationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chronos.services.v1.ChargeLocationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChargeLocationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddDepartureTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chronos.services.v1.ChargeLocationService/AddDepartureTime',
            chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.AddDepartureTimeToChargeLocationRequest.SerializeToString,
            chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.AddDepartureTimeToChargeLocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddTimer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chronos.services.v1.ChargeLocationService/AddTimer',
            chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.AddTimerToChargeLocationRequest.SerializeToString,
            chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.AddTimerToChargeLocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAtTheCarLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chronos.services.v1.ChargeLocationService/CreateAtTheCarLocation',
            chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.CreateAtTheCarLocationRequest.SerializeToString,
            chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.CreateAtTheCarLocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chronos.services.v1.ChargeLocationService/DeleteLocation',
            chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.DeleteChargeLocationRequest.SerializeToString,
            chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.DeleteChargeLocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChargeLocations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chronos.services.v1.ChargeLocationService/GetChargeLocations',
            chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.GetChargeLocationsRequest.SerializeToString,
            chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.GetChargeLocationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def isAtALocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chronos.services.v1.ChargeLocationService/isAtALocation',
            chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.IsAtLocationRequest.SerializeToString,
            chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.IsAtLocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAlias(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chronos.services.v1.ChargeLocationService/UpdateAlias',
            chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationAliasRequest.SerializeToString,
            chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationAliasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAmpLimit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chronos.services.v1.ChargeLocationService/UpdateAmpLimit',
            chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationAmpLimitRequest.SerializeToString,
            chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationAmpLimitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDepartureTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chronos.services.v1.ChargeLocationService/UpdateDepartureTime',
            chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationDepartureTimeRequest.SerializeToString,
            chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationDepartureTimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMinimumSoc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chronos.services.v1.ChargeLocationService/UpdateMinimumSoc',
            chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationMinimumSocRequest.SerializeToString,
            chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationMinimumSocResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateOptimizedSetting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chronos.services.v1.ChargeLocationService/UpdateOptimizedSetting',
            chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateOptimizedSettingRequest.SerializeToString,
            chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateOptimizedSettingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTimer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chronos.services.v1.ChargeLocationService/UpdateTimer',
            chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationTimerRequest.SerializeToString,
            chronos_dot_services_dot_chargelocation_dot_v1_dot_chargelocation__service__pb2.UpdateChargeLocationTimerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
