# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chronos/services/globalchargetimer/v2/globalchargetimer_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chronos/services/globalchargetimer/v2/globalchargetimer_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chronos.messages.common.v1 import common_pb2 as chronos_dot_messages_dot_common_dot_v1_dot_common__pb2
from chronos.entities.globalchargetimer.v2 import globalchargetimer_pb2 as chronos_dot_entities_dot_globalchargetimer_dot_v2_dot_globalchargetimer__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEchronos/services/globalchargetimer/v2/globalchargetimer_service.proto\x12\x13\x63hronos.services.v2\x1a\'chronos/messages/common/v1/common.proto\x1a=chronos/entities/globalchargetimer/v2/globalchargetimer.proto\"\xc0\x01\n\x1bSetGlobalChargeTimerRequest\x12;\n\x07request\x18\x01 \x01(\x0b\x32*.chronos.messages.common.v1.ChronosRequest\x12N\n\x0c\x63harge_timer\x18\x02 \x01(\x0b\x32\x38.chronos.entities.globalchargetimer.v2.GlobalChargeTimer\x12\x14\n\x0ctime_is_utc0\x18\x03 \x01(\x08\"\x88\x01\n\x1cSetGlobalChargeTimerResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x32\n\x06status\x18\x02 \x01(\x0e\x32\".chronos.messages.common.v1.Status\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x17\n\x0fhas_not_changed\x18\x04 \x01(\x08\x32\x97\x01\n\x18GlobalChargeTimerService\x12{\n\x14SetGlobalChargeTimer\x12\x30.chronos.services.v2.SetGlobalChargeTimerRequest\x1a\x31.chronos.services.v2.SetGlobalChargeTimerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chronos.services.globalchargetimer.v2.globalchargetimer_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETGLOBALCHARGETIMERREQUEST']._serialized_start=199
  _globals['_SETGLOBALCHARGETIMERREQUEST']._serialized_end=391
  _globals['_SETGLOBALCHARGETIMERRESPONSE']._serialized_start=394
  _globals['_SETGLOBALCHARGETIMERRESPONSE']._serialized_end=530
  _globals['_GLOBALCHARGETIMERSERVICE']._serialized_start=533
  _globals['_GLOBALCHARGETIMERSERVICE']._serialized_end=684
# @@protoc_insertion_point(module_scope)
