# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chronos/entities/globalchargetimer/v2/globalchargetimer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chronos/entities/globalchargetimer/v2/globalchargetimer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chronos.entities.common.v1 import common_pb2 as chronos_dot_entities_dot_common_dot_v1_dot_common__pb2
from chronos.messages.common.v1 import common_pb2 as chronos_dot_messages_dot_common_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=chronos/entities/globalchargetimer/v2/globalchargetimer.proto\x12%chronos.entities.globalchargetimer.v2\x1a\'chronos/entities/common/v1/common.proto\x1a\'chronos/messages/common/v1/common.proto\"\xc9\x01\n\x11GlobalChargeTimer\x12\x34\n\x05start\x18\x01 \x01(\x0b\x32%.chronos.entities.common.v1.DailyTime\x12\x33\n\x04stop\x18\x02 \x01(\x0b\x32%.chronos.entities.common.v1.DailyTime\x12\x11\n\tactivated\x18\x03 \x01(\x08\x12\x36\n\x08metadata\x18\x04 \x01(\x0b\x32$.chronos.messages.common.v1.Metadatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chronos.entities.globalchargetimer.v2.globalchargetimer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GLOBALCHARGETIMER']._serialized_start=187
  _globals['_GLOBALCHARGETIMER']._serialized_end=388
# @@protoc_insertion_point(module_scope)
