# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: entities/vehiclestates/precleaning/precleaning.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'entities/vehiclestates/precleaning/precleaning.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from entities.common import timestamp_pb2 as entities_dot_common_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4entities/vehiclestates/precleaning/precleaning.proto\x12\"entities.vehiclestates.precleaning\x1a\x1f\x65ntities/common/timestamp.proto\"\xcd\x07\n\x0bPreCleaning\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.entities.common.Timestamp\x12\x38\n\x14last_cycle_completed\x18\x02 \x01(\x0b\x32\x1a.entities.common.Timestamp\x12\x34\n\x10measurement_date\x18\x03 \x01(\x0b\x32\x1a.entities.common.Timestamp\x12.\n\nstarted_at\x18\x04 \x01(\x0b\x32\x1a.entities.common.Timestamp\x12-\n\tending_at\x18\x05 \x01(\x0b\x32\x1a.entities.common.Timestamp\x12U\n\x0erunning_status\x18\x06 \x01(\x0e\x32=.entities.vehiclestates.precleaning.PreCleaning.RunningStatus\x12Q\n\x0cstart_reason\x18\x07 \x01(\x0e\x32;.entities.vehiclestates.precleaning.PreCleaning.StartReason\x12\x18\n\x10last_cycle_valid\x18\x08 \x01(\x08\x12\"\n\x1ameasured_air_quality_index\x18\t \x01(\x05\x12\'\n\x1fmeasured_particulate_matter_2_5\x18\n \x01(\x05\x12\x1c\n\x14runtime_left_minutes\x18\x0b \x01(\x05\x12H\n\x05\x65rror\x18\r \x01(\x0e\x32\x39.entities.vehiclestates.precleaning.PreCleaning.ErrorType\"a\n\tErrorType\x12\x1a\n\x16\x45RROR_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n\x18\x45RROR_TYPE_GENERIC_ERROR\x10\x01\x12\x1a\n\x16\x45RROR_TYPE_INTERRUPTED\x10\x02\"h\n\x0bStartReason\x12\x1c\n\x18START_REASON_UNSPECIFIED\x10\x00\x12\x17\n\x13START_REASON_REMOTE\x10\x01\x12\"\n\x1eSTART_REASON_MANUALLY_FROM_CAR\x10\x02\"z\n\rRunningStatus\x12\x1e\n\x1aRUNNING_STATUS_UNSPECIFIED\x10\x00\x12\x15\n\x11RUNNING_STATUS_ON\x10\x01\x12\x16\n\x12RUNNING_STATUS_OFF\x10\x02\x12\x1a\n\x16RUNNING_STATUS_PENDING\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'entities.vehiclestates.precleaning.precleaning_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRECLEANING']._serialized_start=126
  _globals['_PRECLEANING']._serialized_end=1099
  _globals['_PRECLEANING_ERRORTYPE']._serialized_start=772
  _globals['_PRECLEANING_ERRORTYPE']._serialized_end=869
  _globals['_PRECLEANING_STARTREASON']._serialized_start=871
  _globals['_PRECLEANING_STARTREASON']._serialized_end=975
  _globals['_PRECLEANING_RUNNINGSTATUS']._serialized_start=977
  _globals['_PRECLEANING_RUNNINGSTATUS']._serialized_end=1099
# @@protoc_insertion_point(module_scope)
