# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/vehiclestates/battery/battery_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'services/vehiclestates/battery/battery_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from entities.vehiclestates.battery import battery_pb2 as entities_dot_vehiclestates_dot_battery_dot_battery__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4services/vehiclestates/battery/battery_service.proto\x12\x1eservices.vehiclestates.battery\x1a,entities/vehiclestates/battery/battery.proto\",\n\x11GetBatteryRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03vin\x18\x02 \x01(\t\"g\n\x12GetBatteryResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03vin\x18\x02 \x01(\t\x12\x38\n\x07\x62\x61ttery\x18\x03 \x01(\x0b\x32\'.entities.vehiclestates.battery.Battery2\x8b\x01\n\x0e\x42\x61tteryService\x12y\n\x10GetLatestBattery\x12\x31.services.vehiclestates.battery.GetBatteryRequest\x1a\x32.services.vehiclestates.battery.GetBatteryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.vehiclestates.battery.battery_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETBATTERYREQUEST']._serialized_start=134
  _globals['_GETBATTERYREQUEST']._serialized_end=178
  _globals['_GETBATTERYRESPONSE']._serialized_start=180
  _globals['_GETBATTERYRESPONSE']._serialized_end=283
  _globals['_BATTERYSERVICE']._serialized_start=286
  _globals['_BATTERYSERVICE']._serialized_end=425
# @@protoc_insertion_point(module_scope)
