# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chronos/services/chargenow/v1/chargenow_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chronos/services/chargenow/v1/chargenow_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chronos.messages.common.v1 import common_pb2 as chronos_dot_messages_dot_common_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5chronos/services/chargenow/v1/chargenow_service.proto\x12\x13\x63hronos.services.v1\x1a\'chronos/messages/common/v1/common.proto\"^\n\x1fStartOverrideChargeTimerRequest\x12;\n\x07request\x18\x01 \x01(\x0b\x32*.chronos.messages.common.v1.ChronosRequest\"V\n StartOverrideChargeTimerResponse\x12\x32\n\x06status\x18\x01 \x01(\x0e\x32\".chronos.messages.common.v1.Status\"]\n\x1eStopOverrideChargeTimerRequest\x12;\n\x07request\x18\x01 \x01(\x0b\x32*.chronos.messages.common.v1.ChronosRequest\"U\n\x1fStopOverrideChargeTimerResponse\x12\x32\n\x06status\x18\x01 \x01(\x0e\x32\".chronos.messages.common.v1.Status2\xa3\x02\n\x10\x43hargeNowService\x12\x87\x01\n\x18StartOverrideChargeTimer\x12\x34.chronos.services.v1.StartOverrideChargeTimerRequest\x1a\x35.chronos.services.v1.StartOverrideChargeTimerResponse\x12\x84\x01\n\x17StopOverrideChargeTimer\x12\x33.chronos.services.v1.StopOverrideChargeTimerRequest\x1a\x34.chronos.services.v1.StopOverrideChargeTimerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chronos.services.chargenow.v1.chargenow_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARTOVERRIDECHARGETIMERREQUEST']._serialized_start=119
  _globals['_STARTOVERRIDECHARGETIMERREQUEST']._serialized_end=213
  _globals['_STARTOVERRIDECHARGETIMERRESPONSE']._serialized_start=215
  _globals['_STARTOVERRIDECHARGETIMERRESPONSE']._serialized_end=301
  _globals['_STOPOVERRIDECHARGETIMERREQUEST']._serialized_start=303
  _globals['_STOPOVERRIDECHARGETIMERREQUEST']._serialized_end=396
  _globals['_STOPOVERRIDECHARGETIMERRESPONSE']._serialized_start=398
  _globals['_STOPOVERRIDECHARGETIMERRESPONSE']._serialized_end=483
  _globals['_CHARGENOWSERVICE']._serialized_start=486
  _globals['_CHARGENOWSERVICE']._serialized_end=777
# @@protoc_insertion_point(module_scope)
