# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from chronos.services.chargenow.v1 import chargenow_service_pb2 as chronos_dot_services_dot_chargenow_dot_v1_dot_chargenow__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in chronos/services/chargenow/v1/chargenow_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChargeNowServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartOverrideChargeTimer = channel.unary_unary(
                '/chronos.services.v1.ChargeNowService/StartOverrideChargeTimer',
                request_serializer=chronos_dot_services_dot_chargenow_dot_v1_dot_chargenow__service__pb2.StartOverrideChargeTimerRequest.SerializeToString,
                response_deserializer=chronos_dot_services_dot_chargenow_dot_v1_dot_chargenow__service__pb2.StartOverrideChargeTimerResponse.FromString,
                _registered_method=True)
        self.StopOverrideChargeTimer = channel.unary_unary(
                '/chronos.services.v1.ChargeNowService/StopOverrideChargeTimer',
                request_serializer=chronos_dot_services_dot_chargenow_dot_v1_dot_chargenow__service__pb2.StopOverrideChargeTimerRequest.SerializeToString,
                response_deserializer=chronos_dot_services_dot_chargenow_dot_v1_dot_chargenow__service__pb2.StopOverrideChargeTimerResponse.FromString,
                _registered_method=True)


class ChargeNowServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartOverrideChargeTimer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopOverrideChargeTimer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChargeNowServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartOverrideChargeTimer': grpc.unary_unary_rpc_method_handler(
                    servicer.StartOverrideChargeTimer,
                    request_deserializer=chronos_dot_services_dot_chargenow_dot_v1_dot_chargenow__service__pb2.StartOverrideChargeTimerRequest.FromString,
                    response_serializer=chronos_dot_services_dot_chargenow_dot_v1_dot_chargenow__service__pb2.StartOverrideChargeTimerResponse.SerializeToString,
            ),
            'StopOverrideChargeTimer': grpc.unary_unary_rpc_method_handler(
                    servicer.StopOverrideChargeTimer,
                    request_deserializer=chronos_dot_services_dot_chargenow_dot_v1_dot_chargenow__service__pb2.StopOverrideChargeTimerRequest.FromString,
                    response_serializer=chronos_dot_services_dot_chargenow_dot_v1_dot_chargenow__service__pb2.StopOverrideChargeTimerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chronos.services.v1.ChargeNowService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chronos.services.v1.ChargeNowService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChargeNowService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartOverrideChargeTimer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chronos.services.v1.ChargeNowService/StartOverrideChargeTimer',
            chronos_dot_services_dot_chargenow_dot_v1_dot_chargenow__service__pb2.StartOverrideChargeTimerRequest.SerializeToString,
            chronos_dot_services_dot_chargenow_dot_v1_dot_chargenow__service__pb2.StartOverrideChargeTimerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopOverrideChargeTimer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chronos.services.v1.ChargeNowService/StopOverrideChargeTimer',
            chronos_dot_services_dot_chargenow_dot_v1_dot_chargenow__service__pb2.StopOverrideChargeTimerRequest.SerializeToString,
            chronos_dot_services_dot_chargenow_dot_v1_dot_chargenow__service__pb2.StopOverrideChargeTimerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
