# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from pccs.location.v1 import location_service_pb2 as pccs_dot_location_dot_v1_dot_location__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pccs/location/v1/location_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LocationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLastParkedLocation = channel.unary_unary(
                '/pccs.location.v1.LocationService/GetLastParkedLocation',
                request_serializer=pccs_dot_location_dot_v1_dot_location__service__pb2.LastParkedLocationRequest.SerializeToString,
                response_deserializer=pccs_dot_location_dot_v1_dot_location__service__pb2.LastParkedLocation.FromString,
                _registered_method=True)


class LocationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLastParkedLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LocationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLastParkedLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLastParkedLocation,
                    request_deserializer=pccs_dot_location_dot_v1_dot_location__service__pb2.LastParkedLocationRequest.FromString,
                    response_serializer=pccs_dot_location_dot_v1_dot_location__service__pb2.LastParkedLocation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pccs.location.v1.LocationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pccs.location.v1.LocationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LocationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLastParkedLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pccs.location.v1.LocationService/GetLastParkedLocation',
            pccs_dot_location_dot_v1_dot_location__service__pb2.LastParkedLocationRequest.SerializeToString,
            pccs_dot_location_dot_v1_dot_location__service__pb2.LastParkedLocation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
