# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pccs/location/v1/location_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pccs/location/v1/location_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'pccs/location/v1/location_service.proto\x12\x10pccs.location.v1\"1\n\x0fGoogleTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\"e\n\x08Location\x12\x11\n\tlongitude\x18\x01 \x01(\x01\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x34\n\ttimestamp\x18\x03 \x01(\x0b\x32!.pccs.location.v1.GoogleTimestamp\"(\n\x19LastParkedLocationRequest\x12\x0b\n\x03vin\x18\x01 \x01(\t\"^\n\x12LastParkedLocation\x12\x0b\n\x03vin\x18\x01 \x01(\t\x12,\n\x08location\x18\x02 \x01(\x0b\x32\x1a.pccs.location.v1.Location\x12\r\n\x05stale\x18\x03 \x01(\x08\x32}\n\x0fLocationService\x12j\n\x15GetLastParkedLocation\x12+.pccs.location.v1.LastParkedLocationRequest\x1a$.pccs.location.v1.LastParkedLocationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pccs.location.v1.location_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GOOGLETIMESTAMP']._serialized_start=61
  _globals['_GOOGLETIMESTAMP']._serialized_end=110
  _globals['_LOCATION']._serialized_start=112
  _globals['_LOCATION']._serialized_end=213
  _globals['_LASTPARKEDLOCATIONREQUEST']._serialized_start=215
  _globals['_LASTPARKEDLOCATIONREQUEST']._serialized_end=255
  _globals['_LASTPARKEDLOCATION']._serialized_start=257
  _globals['_LASTPARKEDLOCATION']._serialized_end=351
  _globals['_LOCATIONSERVICE']._serialized_start=353
  _globals['_LOCATIONSERVICE']._serialized_end=478
# @@protoc_insertion_point(module_scope)
