# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chronos/entities/common/v1/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chronos/entities/common/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'chronos/entities/common/v1/common.proto\x12\x1a\x63hronos.entities.common.v1\"1\n\nCoordinate\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"\"\n\x08TimeZone\x12\x16\n\x0eoffset_minutes\x18\x01 \x01(\x05\"b\n\tDailyTime\x12\x0c\n\x04hour\x18\x01 \x01(\x05\x12\x0e\n\x06minute\x18\x02 \x01(\x05\x12\x37\n\ttime_zone\x18\x03 \x01(\x0b\x32$.chronos.entities.common.v1.TimeZone\"0\n\x04\x44\x61te\x12\x0c\n\x04year\x18\x01 \x01(\x05\x12\r\n\x05month\x18\x02 \x01(\x05\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\x05\"Q\n\nSyncStatus\x12\x32\n\x06status\x18\x01 \x01(\x0e\x32\".chronos.entities.common.v1.Status\x12\x0f\n\x07message\x18\x02 \x01(\t*m\n\x06Status\x12\x17\n\x13SYNC_STATUS_UNKNOWN\x10\x00\x12\x0b\n\x07SYNCING\x10\x01\x12\n\n\x06SYNCED\x10\x02\x12\x0c\n\x08RETRYING\x10\x03\x12\x18\n\x14RETRYING_CAR_OFFLINE\x10\x04\x12\t\n\x05\x45RROR\x10\x05*i\n\x0eResponseStatus\x12\x11\n\rUNKNOWN_ERROR\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x14\n\x10VALIDATION_ERROR\x10\x02\x12\x12\n\x0eINTERNAL_ERROR\x10\x03\x12\r\n\tNOT_FOUND\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chronos.entities.common.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=391
  _globals['_STATUS']._serialized_end=500
  _globals['_RESPONSESTATUS']._serialized_start=502
  _globals['_RESPONSESTATUS']._serialized_end=607
  _globals['_COORDINATE']._serialized_start=71
  _globals['_COORDINATE']._serialized_end=120
  _globals['_TIMEZONE']._serialized_start=122
  _globals['_TIMEZONE']._serialized_end=156
  _globals['_DAILYTIME']._serialized_start=158
  _globals['_DAILYTIME']._serialized_end=256
  _globals['_DATE']._serialized_start=258
  _globals['_DATE']._serialized_end=306
  _globals['_SYNCSTATUS']._serialized_start=308
  _globals['_SYNCSTATUS']._serialized_end=389
# @@protoc_insertion_point(module_scope)
