# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/vehiclestates/exterior/exterior_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'services/vehiclestates/exterior/exterior_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from entities.vehiclestates.exterior import exterior_pb2 as entities_dot_vehiclestates_dot_exterior_dot_exterior__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6services/vehiclestates/exterior/exterior_service.proto\x12\x1fservices.vehiclestates.exterior\x1a.entities/vehiclestates/exterior/exterior.proto\"-\n\x12GetExteriorRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03vin\x18\x02 \x01(\t\"k\n\x13GetExteriorResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03vin\x18\x02 \x01(\t\x12;\n\x08\x65xterior\x18\x03 \x01(\x0b\x32).entities.vehiclestates.exterior.Exterior2\x91\x01\n\x0f\x45xteriorService\x12~\n\x11GetLatestExterior\x12\x33.services.vehiclestates.exterior.GetExteriorRequest\x1a\x34.services.vehiclestates.exterior.GetExteriorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.vehiclestates.exterior.exterior_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETEXTERIORREQUEST']._serialized_start=139
  _globals['_GETEXTERIORREQUEST']._serialized_end=184
  _globals['_GETEXTERIORRESPONSE']._serialized_start=186
  _globals['_GETEXTERIORRESPONSE']._serialized_end=293
  _globals['_EXTERIORSERVICE']._serialized_start=296
  _globals['_EXTERIORSERVICE']._serialized_end=441
# @@protoc_insertion_point(module_scope)
