# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: entities/vehiclestates/fuel/fuel.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'entities/vehiclestates/fuel/fuel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from entities.common import timestamp_pb2 as entities_dot_common_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&entities/vehiclestates/fuel/fuel.proto\x12\x1b\x65ntities.vehiclestates.fuel\x1a\x1f\x65ntities/common/timestamp.proto\"\x82\x02\n\x04\x46uel\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.entities.common.Timestamp\x12\x1c\n\x14\x64istance_to_empty_km\x18\x02 \x01(\x05\x12\x32\n*average_fuel_consumption_liters_per_100_km\x18\x03 \x01(\x01\x12\x1a\n\x12\x66uel_amount_liters\x18\x04 \x01(\x02\x12\x1f\n\x17\x64istance_to_empty_miles\x18\x05 \x01(\x05\x12<\n4average_fuel_consumption_liters_per_100_km_automatic\x18\x06 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'entities.vehiclestates.fuel.fuel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FUEL']._serialized_start=105
  _globals['_FUEL']._serialized_end=363
# @@protoc_insertion_point(module_scope)
