# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chronos/services/parkingclimate/v1/parkingclimate_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chronos/services/parkingclimate/v1/parkingclimate_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chronos.messages.common.v1 import common_pb2 as chronos_dot_messages_dot_common_dot_v1_dot_common__pb2
from chronos.messages.parkingclimate.v1 import parkingclimate_messages_pb2 as chronos_dot_messages_dot_parkingclimate_dot_v1_dot_parkingclimate__messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?chronos/services/parkingclimate/v1/parkingclimate_service.proto\x12\x13\x63hronos.services.v1\x1a\'chronos/messages/common/v1/common.proto\x1a@chronos/messages/parkingclimate/v1/parkingclimate_messages.proto\"\xcc\x01\n\x1eSetParkingClimateTimersRequest\x12;\n\x07request\x18\x01 \x01(\x0b\x32*.chronos.messages.common.v1.ChronosRequest\x12W\n\x16parking_climate_timers\x18\x02 \x03(\x0b\x32\x37.chronos.messages.parkingclimate.v1.ParkingClimateTimer\x12\x14\n\x0ctime_is_utc0\x18\x03 \x01(\x08\"\x7f\n\x1fSetParkingClimateTimersResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03vin\x18\x02 \x01(\t\x12\x32\n\x06status\x18\x03 \x01(\x0e\x32\".chronos.messages.common.v1.Status\x12\x0f\n\x07message\x18\x04 \x01(\t\"\xaf\x01\n%SetParkingClimateTimerSettingsRequest\x12;\n\x07request\x18\x01 \x01(\x0b\x32*.chronos.messages.common.v1.ChronosRequest\x12I\n\x0etimer_settings\x18\x02 \x01(\x0b\x32\x31.chronos.messages.parkingclimate.v1.TimerSettings\"m\n&SetParkingClimateTimerSettingsResponse\x12\x32\n\x06status\x18\x01 \x01(\x0e\x32\".chronos.messages.common.v1.Status\x12\x0f\n\x07message\x18\x02 \x01(\t2\xa4\x02\n\x1aParkingClimateTimerService\x12x\n\tSetTimers\x12\x33.chronos.services.v1.SetParkingClimateTimersRequest\x1a\x34.chronos.services.v1.SetParkingClimateTimersResponse0\x01\x12\x8b\x01\n\x10SetTimerSettings\x12:.chronos.services.v1.SetParkingClimateTimerSettingsRequest\x1a;.chronos.services.v1.SetParkingClimateTimerSettingsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chronos.services.parkingclimate.v1.parkingclimate_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETPARKINGCLIMATETIMERSREQUEST']._serialized_start=196
  _globals['_SETPARKINGCLIMATETIMERSREQUEST']._serialized_end=400
  _globals['_SETPARKINGCLIMATETIMERSRESPONSE']._serialized_start=402
  _globals['_SETPARKINGCLIMATETIMERSRESPONSE']._serialized_end=529
  _globals['_SETPARKINGCLIMATETIMERSETTINGSREQUEST']._serialized_start=532
  _globals['_SETPARKINGCLIMATETIMERSETTINGSREQUEST']._serialized_end=707
  _globals['_SETPARKINGCLIMATETIMERSETTINGSRESPONSE']._serialized_start=709
  _globals['_SETPARKINGCLIMATETIMERSETTINGSRESPONSE']._serialized_end=818
  _globals['_PARKINGCLIMATETIMERSERVICE']._serialized_start=821
  _globals['_PARKINGCLIMATETIMERSERVICE']._serialized_end=1113
# @@protoc_insertion_point(module_scope)
