# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: entities/vehiclestates/engineremotestart/engineremotestart.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'entities/vehiclestates/engineremotestart/engineremotestart.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from entities.common import timestamp_pb2 as entities_dot_common_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@entities/vehiclestates/engineremotestart/engineremotestart.proto\x12(entities.vehiclestates.engineremotestart\x1a\x1f\x65ntities/common/timestamp.proto\"\x8c\x08\n\x11\x45ngineRemoteStart\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.entities.common.Timestamp\x12\x61\n\x0erunning_status\x18\x02 \x01(\x0e\x32I.entities.vehiclestates.engineremotestart.EngineRemoteStart.RunningStatus\x12T\n\x05\x65rror\x18\x03 \x01(\x0e\x32\x45.entities.vehiclestates.engineremotestart.EngineRemoteStart.ErrorType\x12.\n\nstarted_at\x18\x04 \x01(\x0b\x32\x1a.entities.common.Timestamp\x12-\n\tending_at\x18\x05 \x01(\x0b\x32\x1a.entities.common.Timestamp\"\x8f\x04\n\tErrorType\x12\x1a\n\x16\x45RROR_TYPE_UNSPECIFIED\x10\x00\x12#\n\x1f\x45RROR_TYPE_EXCEEDED_MAX_ATTEMPT\x10\x01\x12\x1b\n\x17\x45RROR_TYPE_CAR_UNLOCKED\x10\x02\x12\x19\n\x15\x45RROR_TYPE_KEY_IN_CAR\x10\x03\x12\x18\n\x14\x45RROR_TYPE_DOOR_OPEN\x10\x04\x12\x18\n\x14\x45RROR_TYPE_HOOD_OPEN\x10\x05\x12\x1d\n\x19\x45RROR_TYPE_INCORRECT_GEAR\x10\x06\x12\x1c\n\x18\x45RROR_TYPE_PERSON_IN_CAR\x10\x07\x12\x1c\n\x18\x45RROR_TYPE_PEDAL_PRESSED\x10\x08\x12\x17\n\x13\x45RROR_TYPE_LOW_FUEL\x10\t\x12\x1a\n\x16\x45RROR_TYPE_LOW_BATTERY\x10\n\x12#\n\x1f\x45RROR_TYPE_LOW_BATTERY_AND_FUEL\x10\x0b\x12\x1e\n\x1a\x45RROR_TYPE_CHARGER_PLUGGED\x10\x0c\x12#\n\x1f\x45RROR_TYPE_ENGINE_COOLANT_FAULT\x10\r\x12$\n ERROR_TYPE_BATTERY_COOLANT_FAULT\x10\x0e\x12\x1f\n\x1b\x45RROR_TYPE_SERVICE_REQUIRED\x10\x0f\x12\x14\n\x10\x45RROR_TYPE_OTHER\x10\x10\"\x9d\x01\n\rRunningStatus\x12\x1e\n\x1aRUNNING_STATUS_UNSPECIFIED\x10\x00\x12\x16\n\x12RUNNING_STATUS_OFF\x10\x01\x12\x1b\n\x17RUNNING_STATUS_STARTING\x10\x02\x12\x1a\n\x16RUNNING_STATUS_RUNNING\x10\x03\x12\x1b\n\x17RUNNING_STATUS_STOPPING\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'entities.vehiclestates.engineremotestart.engineremotestart_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENGINEREMOTESTART']._serialized_start=144
  _globals['_ENGINEREMOTESTART']._serialized_end=1180
  _globals['_ENGINEREMOTESTART_ERRORTYPE']._serialized_start=493
  _globals['_ENGINEREMOTESTART_ERRORTYPE']._serialized_end=1020
  _globals['_ENGINEREMOTESTART_RUNNINGSTATUS']._serialized_start=1023
  _globals['_ENGINEREMOTESTART_RUNNINGSTATUS']._serialized_end=1180
# @@protoc_insertion_point(module_scope)
