# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: entities/vehiclestates/odometer/odometer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'entities/vehiclestates/odometer/odometer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from entities.common import timestamp_pb2 as entities_dot_common_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.entities/vehiclestates/odometer/odometer.proto\x12\x1f\x65ntities.vehiclestates.odometer\x1a\x1f\x65ntities/common/timestamp.proto\"\xb5\x02\n\x08Odometer\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.entities.common.Timestamp\x12\x17\n\x0fodometer_meters\x18\x02 \x01(\x05\x12\x1c\n\x14trip_meter_manual_km\x18\x03 \x01(\x02\x12\x1f\n\x17trip_meter_automatic_km\x18\x04 \x01(\x02\x12!\n\x19\x61verage_speed_km_per_hour\x18\x05 \x01(\x05\x12+\n#average_speed_km_per_hour_automatic\x18\x06 \x01(\x05\x12\"\n\x1atrip_meter_since_charge_km\x18\x07 \x01(\x02\x12.\n&average_speed_km_per_hour_since_charge\x18\x08 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'entities.vehiclestates.odometer.odometer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ODOMETER']._serialized_start=117
  _globals['_ODOMETER']._serialized_end=426
# @@protoc_insertion_point(module_scope)
