# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/vehiclestates/parkingclimatization/parkingclimatization_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'services/vehiclestates/parkingclimatization/parkingclimatization_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from entities.vehiclestates.parkingclimatization import parkingclimatization_pb2 as entities_dot_vehiclestates_dot_parkingclimatization_dot_parkingclimatization__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nNservices/vehiclestates/parkingclimatization/parkingclimatization_service.proto\x12+services.vehiclestates.parkingclimatization\x1a\x46\x65ntities/vehiclestates/parkingclimatization/parkingclimatization.proto\"9\n\x1eGetParkingClimatizationRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03vin\x18\x02 \x01(\t\"\x9c\x01\n\x1fGetParkingClimatizationResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03vin\x18\x02 \x01(\t\x12`\n\x15parking_climatization\x18\x03 \x01(\x0b\x32\x41.entities.vehiclestates.parkingclimatization.ParkingClimatization2\xda\x01\n\x1bParkingClimatizationService\x12\xba\x01\n\x1dGetLatestParkingClimatization\x12K.services.vehiclestates.parkingclimatization.GetParkingClimatizationRequest\x1aL.services.vehiclestates.parkingclimatization.GetParkingClimatizationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.vehiclestates.parkingclimatization.parkingclimatization_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPARKINGCLIMATIZATIONREQUEST']._serialized_start=199
  _globals['_GETPARKINGCLIMATIZATIONREQUEST']._serialized_end=256
  _globals['_GETPARKINGCLIMATIZATIONRESPONSE']._serialized_start=259
  _globals['_GETPARKINGCLIMATIZATIONRESPONSE']._serialized_end=415
  _globals['_PARKINGCLIMATIZATIONSERVICE']._serialized_start=418
  _globals['_PARKINGCLIMATIZATIONSERVICE']._serialized_end=636
# @@protoc_insertion_point(module_scope)
