# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chronos/messages/common/v1/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chronos/messages/common/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chronos.entities.common.v1 import common_pb2 as chronos_dot_entities_dot_common_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'chronos/messages/common/v1/common.proto\x12\x1a\x63hronos.messages.common.v1\x1a\'chronos/entities/common/v1/common.proto\"r\n\x0e\x43hronosRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03vin\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x37\n\ttime_zone\x18\x04 \x01(\x0b\x32$.chronos.entities.common.v1.TimeZone\"\x91\x01\n\x08Metadata\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nupdated_at\x18\x02 \x01(\x03\x12\x0e\n\x06source\x18\x03 \x01(\t\x12;\n\x0bsync_status\x18\x04 \x01(\x0b\x32&.chronos.entities.common.v1.SyncStatus\x12\x18\n\x10source_timestamp\x18\x05 \x01(\x03*\x86\x01\n\x06Status\x12\x11\n\rUNKNOWN_ERROR\x10\x00\x12\x08\n\x04SENT\x10\x01\x12\r\n\tDELIVERED\x10\x02\x12\x0b\n\x07SUCCESS\x10\x03\x12\n\n\x06SYNCED\x10\x04\x12\x0f\n\x0b\x43\x41R_OFFLINE\x10\x05\x12\r\n\tCAR_ERROR\x10\x06\x12\t\n\x05\x45RROR\x10\x07\x12\x0c\n\x08REPLACED\x10\x08*~\n\x07Weekday\x12\x17\n\x13WEEKDAY_UNSPECIFIED\x10\x00\x12\n\n\x06MONDAY\x10\x01\x12\x0b\n\x07TUESDAY\x10\x02\x12\r\n\tWEDNESDAY\x10\x03\x12\x0c\n\x08THURSDAY\x10\x04\x12\n\n\x06\x46RIDAY\x10\x05\x12\x0c\n\x08SATURDAY\x10\x06\x12\n\n\x06SUNDAY\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chronos.messages.common.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=377
  _globals['_STATUS']._serialized_end=511
  _globals['_WEEKDAY']._serialized_start=513
  _globals['_WEEKDAY']._serialized_end=639
  _globals['_CHRONOSREQUEST']._serialized_start=112
  _globals['_CHRONOSREQUEST']._serialized_end=226
  _globals['_METADATA']._serialized_start=229
  _globals['_METADATA']._serialized_end=374
# @@protoc_insertion_point(module_scope)
